sonar.projectKey=dgNeWork_concompas-backend
sonar.organization=dgnework

sonar.sources=src
sonar.exclusions=src/**/*.spec.ts

sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
